//! Templates — AGENTS.md + .cursorrules generated by `palskills-engine init`.
//!
//! These instruct any AI agent (Cursor, opencode, Claude Code, Codex) to follow
//! the palskills pipeline. Generated once at init; existing files are never
//! overwritten (user customizations win).

use std::path::{Path, PathBuf};
use anyhow::Result;

const AGENTS_MD: &str = r#"# AGENTS.md — Palskills Pipeline Instructions

This project uses the **palskills-engine** MCP server (6 tools) for all
AI-assisted development. Every task MUST follow the pipeline below.

## Pipeline (MANDATORY — follow this order)

```
orchestrate → plan → scan_context → dispatch → run_tests → record_session
     ↓         ↓          ↓            ↓            ↓            ↓
  flow +    group 3+   ALL context   SOLID +     verify      WRITE
  intent    issues     (CBM+palbox)  quality     + impact    KNOWLEDGE
```

- **orchestrate** — detect task intent, get flow + confidence
- **plan** — if 3+ issues: group by dependency FIRST (root cause → shared → independent), one plan per group
- **scan_context** — READ ALL knowledge (CBM symbols, decisions, modules, api, lessons, plans)
- **dispatch** — read SOLID + observability contract BEFORE writing code
- **run_tests** — verify, fix, re-run
- **record_session** — WRITE knowledge (summary mandatory; decisions/modules/api/lessons when applicable)

## Git Auto-Knowledge (pending commits)

Commits are auto-captured to `.palbox/pending/` via post-commit hook.

1. **scan_context** will flag: `⚠️ N unrecorded git commits`
2. When you see this, read the pending commit metadata (files changed, messages)
3. At the end of the task, call `record_session` — the engine shows pending as context;
   you fill the WHY (decisions, lessons, api). Pending is then marked recorded.
4. If a task completes without recording, the pending stays — it is never lost.
   Future sessions will surface it again.

## Knowledge Base Rules

- `.palbox/` is a KNOWLEDGE BASE, not a file list
- `record_session` MUST be called at the end of every completed task
- Record WHY (decisions), not just WHAT (file lists)
- Never re-scan what scan_context already provides — use the tools
- No manual grep/rg browsing when CBM tools are available

## Code Quality (from dispatch)

- SOLID principles — SRP, OCP, LSP, ISP, DIP
- Guard clauses (early return + throw) are ENCOURAGED — do NOT refactor
  validation guards into polymorphism
- if-else/switch CHAINS (3+ branches selecting behavior by same type) are
  FORBIDDEN — use polymorphism/strategy/lookup maps instead
- Observability: every HTTP request = ONE structured log row; use framework
  built-in logger first (NestJS Logger, Express middleware); never log secrets
- Max 2 levels of nesting; early return over nested if

## Language

- All code, comments, commits, and docs in **English**
"#;

const CURSOR_RULES: &str = r#"# Palskills Engine — AI Agent Rules
# Generated by `palskills-engine init` — v3.6.x pipeline

## Pipeline (MANDATORY — follow this order)

```
orchestrate → plan → scan_context → dispatch → run_tests → record_session
     ↓         ↓          ↓            ↓            ↓            ↓
  flow +    group 3+   ALL context   SOLID +     verify      WRITE
  intent    issues     (CBM+palbox)  quality     + impact    KNOWLEDGE
```

### 1. orchestrate
Analyze task intent + generate advisory plan (auto-saved to .palbox/plans/).
Returns flow, confidence %, CBM symbols/files. NO blocking — proceed immediately.

### 2. plan (multi-issue only)
If the request has 3+ issues, call `plan` FIRST: engine groups by dependency
(root cause → shared state machine → independent), writes ONE plan file per
group to .palbox/plans/. Follow group order — root cause first.

### 3. scan_context — THE context source
**Semua knowledge ada di sini:**
- CBM symbols/files (code)
- `decisions` — kenapa arsitektur begini
- `modules` — tiap module ngapain
- `api_contracts` — endpoint + request/response
- `lessons` — gotchas, hal yang pernah salah
- `architecture`, `database`, `recent_flows`, `recent_sessions`, `latest_plan`
- `pending_commits` — unrecorded git commits waiting for consolidation
- **READ ALL OF IT** sebelum nulis kode — itu peta project lo

### 4. dispatch — SOLID + quality gate (zero I/O)
Read the contract. Apply it. Guard clauses are GOOD; if-else/switch CHAINS are not.

### 5. run_tests
Auto-detect runner (pytest, cargo test, npm test). Fail → fix → re-run.

### 6. record_session — WRITE KNOWLEDGE (MANDATORY)
Call at the end of EVERY completed task. The engine shows unrecorded pending
commits as context — you fill the WHY (decisions, lessons, api).
**Rule: kalau gak ada knowledge buat di-record, minimal summary WAJIB ada.**

## Git auto-knowledge
- Commit → post-commit hook → .palbox/pending/ (metadata only, automatic)
- scan_context flags unrecorded pending → consolidate via record_session
- Pending is never lost — future sessions surface it again

## Key rules
- `scan_context` = satu-satunya context source — dispatch cuma discipline
- No grep/rg/manual browsing — tools cover everything
- `record_session` MANDATORY — kalau di-skip, knowledge loop putus
- Knowledge = WHY + WHAT, bukan list file
- No blocking gates — proceed immediately
"#;

/// Write AGENTS.md + .cursorrules into project_root (never overwrite existing).
pub fn generate(project_root: &Path) -> Result<Vec<PathBuf>> {
    let mut written = vec![];

    let agents_path = project_root.join("AGENTS.md");
    if !agents_path.exists() {
        std::fs::write(&agents_path, AGENTS_MD)?;
        written.push(agents_path);
    }

    let rules_path = project_root.join(".cursorrules");
    if !rules_path.exists() {
        std::fs::write(&rules_path, CURSOR_RULES)?;
        written.push(rules_path);
    }

    Ok(written)
}
